import React, { useState, useMemo } from 'react';
import { GoogleGenAI } from "@google/genai";

const ImageEditorPage: React.FC = () => {
    const ai = useMemo(() => new GoogleGenAI({ apiKey: process.env.API_KEY as string }), []);
    const [prompt, setPrompt] = useState('');
    const [generatedImage, setGeneratedImage] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleGenerateImage = async () => {
        if (!prompt.trim()) {
            setError('請輸入圖片描述！');
            return;
        }
        setIsLoading(true);
        setError(null);
        setGeneratedImage(null);

        const fullPrompt = `"${prompt}", Cute chibi character, vector art, flat design, soft pastel colors, oversized round eyes, simple clean lines, no shadows or gradients`;

        try {
            const response = await ai.models.generateImages({
                model: 'imagen-4.0-generate-001',
                prompt: fullPrompt,
                config: {
                    numberOfImages: 1,
                    outputMimeType: 'image/jpeg',
                    aspectRatio: '1:1',
                },
            });

            if (response.generatedImages && response.generatedImages.length > 0) {
                const base64ImageBytes = response.generatedImages[0].image.imageBytes;
                const imageUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
                setGeneratedImage(imageUrl);
            } else {
                setError('無法生成圖片，請稍後再試。');
            }
        } catch (e) {
            console.error(e);
            setError('生成圖片時發生錯誤，請檢查您的提示或稍後再試。');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="animate-fade-in space-y-8 max-w-4xl mx-auto">
            <div className="text-center bg-white/60 backdrop-blur-sm rounded-xl p-6 shadow-md">
                <h2 className="text-3xl font-extrabold text-gray-800">AI 圖像生成</h2>
                <p className="text-gray-500 mt-2">
                    輸入你想要的畫面，Goodi AI 就會幫你畫出來！<br/>
                    <span className="text-sm">例如：「一個正在看書的可愛小兔子」</span>
                </p>
            </div>

            <div className="bg-white/80 backdrop-blur-md rounded-2xl shadow-xl p-6 space-y-4">
                <div className="flex items-center gap-4">
                    <input
                        type="text"
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="請在這裡輸入圖片描述..."
                        className="w-full p-3 border border-gray-300 bg-white rounded-lg text-lg focus:ring-2 focus:ring-purple-500"
                        disabled={isLoading}
                    />
                    <button
                        onClick={handleGenerateImage}
                        disabled={isLoading}
                        className="bg-purple-600 text-white font-bold px-6 py-3 rounded-lg hover:bg-purple-700 transition-colors whitespace-nowrap text-lg disabled:bg-purple-300 flex items-center justify-center"
                    >
                        {isLoading ? (
                            <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                        ) : '生成圖片'}
                    </button>
                </div>
                 <p className="text-xs text-gray-500 text-center">
                    圖片風格將統一為可愛插畫風，並生成為 1:1 的正方形圖片。
                </p>
            </div>

            <div className="bg-white/80 backdrop-blur-md rounded-2xl shadow-xl p-6 min-h-[300px] flex items-center justify-center">
                {isLoading && (
                    <div className="text-center text-gray-600">
                        <img src="https://api.iconify.design/twemoji/artist-palette.svg" alt="畫畫中" className="w-16 h-16 mx-auto animate-bounce mb-4" />
                        <p className="font-semibold text-lg">Goodi 正在努力畫畫中...</p>
                        <p>請稍等一下下喔！</p>
                    </div>
                )}
                {error && <p className="text-red-500 font-semibold">{error}</p>}
                {generatedImage && (
                    <div className="w-full">
                        <img src={generatedImage} alt="Generated by AI" className="rounded-lg shadow-md mx-auto w-full object-contain" />
                    </div>
                )}
                {!isLoading && !error && !generatedImage && (
                    <div className="text-center text-gray-400">
                        <img src="https://api.iconify.design/twemoji/frame-with-picture.svg" alt="圖片顯示區域" className="w-20 h-20 mx-auto mb-4" />
                        <p>生成的圖片將會顯示在這裡</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ImageEditorPage;